### ISSUE TITLE
拍照出的照片怎么才能和设置的提示线大小一致呢？

### ISSUE THREAD

**Issue by cnzlh** [MiaoShichang/MSCTakePhoto#1]
把身份证置于框内，但是拍出来的照片包括阴影部分的图像

**Comment by MiaoShichang** [comment]
目前是包括阴影部分的，没有做裁剪功能，其实我们的项目需求是要求上传的照片上传到服务器后，身份证在后台审核时身份证的人头要朝上，清晰即可，所以也就没有做相应的裁剪，  这个demo其实就是为了让上传的身份证的照片清晰可辨，没有其他功能。不知道你为什么一定要照片和提示线大小一致？我感觉这是没必要的，因为每个人和每个人拍出来的照片都不一样，这个提示框只是一个大概的提示作用，没有其他用途。只能给你解析到这了，如果还有什么疑问，欢迎提问^_^
